services:
  api:
    image: aribowobob/pos-be
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432/pos_db"
      JWT_SECRET: ${JWT_SECRET}
      ENVIRONMENT: "production"
      FRONTEND_URLS: ${FRONTEND_URLS}
      PORT: 8080
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - pos-network

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: pos_db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pos_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - pos-network

networks:
  pos-network:
    driver: bridge

volumes:
  db:
    driver: local
