[target.'cfg(all())']
rustflags = [
    "-Dwarnings",
    "-Wclippy::all",
    "-Wclippy::pedantic",
    "-Aclippy::module_name_repetitions",
    "-Aclippy::too_many_lines",
    "-Aclippy::missing_errors_doc",
    "-Aclippy::missing_panics_doc",
]

[alias]
# Use direct commands instead of recursive aliases
w = "watch -x 'run'"
dev = "watch -x check -x test -x run"
